services:
  fin-tracker:
    build:
      context: .docker
      dockerfile: Dockerfile-dev
    container_name: fin-tracker
    ports:
      - '${APP_PORT:-8080}:80'
    volumes:
      - '.:/app'
  fin-tracker-db:
    image: mariadb:11.4
    container_name: fin-tracker-db
    ports:
      - '3306:3306'
    environment:
      - MARIADB_DATABASE=${DB_DATABASE:-fin-tracker}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-root}
