services:
  fin-tracker:
    build:
      context: docker
      dockerfile: Dockerfile-dev
    pull_policy: never
    image: barthjs/fin-tracker:dev
    container_name: fin-tracker
    ports:
      - 80:80
      - 5173:5173
    volumes:
      - ./:/app
    extra_hosts:
      - host.docker.internal:host-gateway

  mariadb:
    image: mariadb:11.4
    container_name: fin-tracker-db
    ports:
      - 3306:3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}

volumes:
  db:
