services:
  app:
    extends:
      file: .docker/compose.base.yaml
      service: app
    build:
      args:
        image: "webdevops/php-apache-dev:8.3-alpine"
    environment:
      - PHP_DEBUGGER=xdebug
      - PHP_DISPLAY_ERRORS=1
      - PHP_IDE_CONFIG=serverName=fin-tracker
      - XDEBUG_CLIENT_PORT=9003
      - XDEBUG_CLIENT_HOST=host.docker.internal
      - XDEBUG_START_WITH_REQUEST=yes
  db:
    extends:
      file: .docker/compose.base.yaml
      service: db
