services:
  fin-tracker:
    build:
      context: docker
      dockerfile: Dockerfile-dev
    pull_policy: never
    image: barthjs/fin-tracker:dev
    container_name: fin-tracker
    ports:
      - 80:80
      - 5173:5173
    volumes:
      - ./:/app
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: postgres:17-alpine
    container_name: fin-tracker-db
    working_dir: /pgsqldump
    ports:
      - 5432:5432
    volumes:
      - ./database:/pgsqldump
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db:
