<?php

declare(strict_types=1);

namespace App\Filament\Pages\Auth;

use App\Enums\ApiAbility;
use App\Filament\Concerns\HasResourceFormFields;
use App\Models\User;
use App\Services\Oidc\OidcService;
use App\Services\UserService;
use Carbon\CarbonImmutable;
use Closure;
use Filament\Actions\Action;
use Filament\Facades\Filament;
use Filament\Forms\Components\Checkbox;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\TextInput;
use Filament\Infolists\Components\TextEntry;
use Filament\Notifications\Notification;
use Filament\Schemas\Components\Actions;
use Filament\Schemas\Components\Component;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Components\Utilities\Set;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Width;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Str;
use Jenssegers\Agent\Agent;
use Laravel\Sanctum\PersonalAccessToken;

final class EditProfile extends \Filament\Auth\Pages\EditProfile
{
    use HasResourceFormFields;

    /** @var array<array{label: string, is_connected: bool, id?: int|string|null}> */
    public array $oidcProviders = [];

    /** @var \Illuminate\Database\Eloquent\Collection<int, PersonalAccessToken> */
    public Collection $apiTokens;

    public ?string $newApiToken = null;

    /**
     * @var array<int, array{
     *     device: array{
     *         is_desktop: bool,
     *         platform: bool|string,
     *         browser: bool|string
     *     },
     *     ip_address: string|null,
     *     is_current_device: bool,
     *     last_active: int
     * }>
     */
    public array $sessions = [];

    protected string $view = 'filament.pages.auth.edit-profile';

    private bool $wasUnverified = false;

    public static function isSimple(): bool
    {
        return ! auth()->user()->is_verified;
    }

    public function mount(): void
    {
        parent::mount();

        $this->loadOidcProviders();
        $this->loadSessions();
        $this->loadApiTokens();

        if (auth()->user()->password === null) {
            Filament::getCurrentOrDefaultPanel()?->multiFactorAuthentication([]);
        }
    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                self::logoField('avatar', 'users/avatars')
                    ->label(__('user.fields.avatar')),

                $this->getFirstNameFormComponent(),
                $this->getLastNameFormComponent(),
                $this->getEmailFormComponent(),
                $this->getUsernameFormComponent(),

                $this->getCurrentPasswordFormComponent(),
                $this->getPasswordFormComponent(),
                $this->getPasswordConfirmationFormComponent(),
            ]);
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        // Users generated by admins are not verified by default.
        /** @var User $record */
        if (! $record->is_verified && isset($data['password'])) {
            $this->wasUnverified = true;
            $record->is_verified = true;
        }

        return parent::handleRecordUpdate($record, $data);
    }

    protected function getRedirectUrl(): ?string
    {
        return $this->wasUnverified ? Filament::getUrl() : null;
    }

    protected function getFirstNameFormComponent(): Component
    {
        return TextInput::make('first_name')
            ->label(__('user.fields.first_name'))
            ->maxLength(255);
    }

    protected function getLastNameFormComponent(): Component
    {
        return TextInput::make('last_name')
            ->label(__('user.fields.last_name'))
            ->maxLength(255);
    }

    protected function getUsernameFormComponent(): Component
    {
        return TextInput::make('username')
            ->label(__('user.fields.username'))
            ->required()
            ->maxLength(255)
            ->unique(ignoreRecord: true)
            ->live(debounce: 500);
    }

    protected function getCurrentPasswordFormComponent(): Component
    {
        /** @var User $user */
        $user = auth()->user();

        return TextInput::make('currentPassword')
            ->label(__('filament-panels::auth/pages/edit-profile.form.current_password.label'))
            ->validationAttribute(__('filament-panels::auth/pages/edit-profile.form.current_password.validation_attribute'))
            ->password()
            ->autocomplete('current-password')
            ->currentPassword(guard: Filament::getAuthGuard())
            ->revealable()
            ->visible(fn (): bool => $user->getAttributeValue('password') !== null)
            ->required(fn (Get $get): bool => $user->getAttributeValue('password') !== null && (
                filled($get('password'))
                || ($get('email') !== $user->getAttributeValue('email'))
                || ($get('username') !== $user->getAttributeValue('username'))
            ))
            ->dehydrated(false);
    }

    protected function getPasswordFormComponent(): TextInput
    {
        /** @var User $user */
        $user = auth()->user();

        /** @var TextInput $field */
        $field = parent::getPasswordFormComponent();

        return $field->label(fn (): string => $user->password === null
            ? (string) __('profile.set_password_to_convert')
            : (string) __('filament-panels::auth/pages/edit-profile.form.password.label'))
            ->required(fn (): bool => $user->password === null && $user->providers()->count() === 0);
    }

    protected function removeProviderAction(): Action
    {
        $user = auth()->user();

        return Action::make('removeProvider')
            ->icon('tabler-trash')
            ->color('danger')
            ->size('sm')
            ->label(__('profile.oidc.remove'))
            ->requiresConfirmation()
            ->disabled(fn (): bool => ($user->password === null && $user->providers()->count() <= 1))
            ->action(function (array $arguments) use ($user): void {
                $user->providers()->where('id', $arguments['id'])->delete();
                $this->loadOidcProviders();

                Notification::make()
                    ->success()
                    ->title(__('profile.oidc.removed'))
                    ->send();
            });
    }

    protected function createApiTokenAction(): Action
    {
        return Action::make('createApiToken')
            ->icon('tabler-plus')
            ->color('primary')
            ->size('sm')
            ->label(__('profile.api_tokens.create'))
            ->mountUsing(fn () => $this->newApiToken = null)
            ->schema([
                TextInput::make('plain_token')
                    ->label(__('profile.api_tokens.token_value'))
                    ->helperText(__('profile.api_tokens.token_warning'))
                    ->visible(fn (): bool => filled($this->newApiToken))
                    ->readonly()
                    ->copyable(),

                TextInput::make('name')
                    ->label(__('profile.api_tokens.name'))
                    ->required()
                    ->maxLength(255)
                    ->autofocus()
                    ->hidden(fn (): bool => filled($this->newApiToken))
                    ->rules([
                        fn (Get $get): Closure => function (string $attribute, mixed $value, Closure $fail) use ($get): void {
                            /** @var array<string, bool> $abilities */
                            $abilities = $get('abilities') ?? [];

                            if (! in_array(true, $abilities, true)) {
                                $fail(__('profile.api_tokens.min_abilities'));
                            }
                        },
                    ]),

                Section::make(__('profile.api_tokens.abilities'))
                    ->hidden(fn (): bool => filled($this->newApiToken))
                    ->schema([
                        Actions::make([
                            Action::make('selectAll')
                                ->icon('tabler-checks')
                                ->size('sm')
                                ->label(__('profile.api_tokens.select_all'))
                                ->action(function (Set $set): void {
                                    foreach (ApiAbility::cases() as $ability) {
                                        $set("abilities.{$ability->read()}", true);
                                        $set("abilities.{$ability->write()}", true);
                                    }
                                }),

                            Action::make('deselectAll')
                                ->icon('tabler-x')
                                ->color('gray')
                                ->size('sm')
                                ->label(__('profile.api_tokens.deselect_all'))
                                ->action(fn (Set $set) => $set('abilities', [])),
                        ])->columnSpanFull(),
                        ...collect(ApiAbility::cases())->map(function (ApiAbility $ability): Component {
                            $readKey = $ability->read();
                            $writeKey = $ability->write();

                            return Grid::make()
                                ->columns(3)
                                ->schema([
                                    TextEntry::make("label_$ability->value}")
                                        ->hiddenLabel()
                                        ->state(Str::ucfirst(__("$ability->value.plural_label"))),

                                    Checkbox::make("abilities.$readKey")
                                        ->label(__('profile.api_tokens.read'))
                                        ->live(),

                                    Checkbox::make("abilities.$writeKey")
                                        ->label(__('profile.api_tokens.write'))
                                        ->live()
                                        ->afterStateUpdated(function (mixed $state, Set $set) use ($readKey): void {
                                            if ($state) {
                                                $set("abilities.$readKey", true);
                                            }
                                        }),
                                ]);
                        })->all(),
                    ]),

                DatePicker::make('expires_at')
                    ->label(__('profile.api_tokens.expires_at'))
                    ->hidden(fn (): bool => filled($this->newApiToken)),
            ])
            ->modalSubmitAction(fn (Action $action): false|Action => filled($this->newApiToken) ? false : $action)
            ->modalCancelActionLabel(fn (): ?string => filled($this->newApiToken) ? (string) __('profile.api_tokens.close') : null)
            ->action(function (array $data, Action $action, Schema $form): void {
                /** @var array{name: string, abilities: array<string, bool>, expires_at: string|null} $data */
                $selectedAbilities = array_keys(array_filter(
                    $data['abilities'],
                    fn (bool $value): bool => $value === true
                ));

                $expiresAt = is_string($data['expires_at'])
                    ? CarbonImmutable::parse($data['expires_at'])
                    : null;

                $token = auth()->user()->createToken($data['name'], $selectedAbilities, $expiresAt);

                $this->newApiToken = $token->plainTextToken;
                $form->fill([
                    'plain_token' => $this->newApiToken,
                ]);

                $this->loadApiTokens();
                $action->halt();
            });
    }

    protected function deleteApiTokenAction(): Action
    {
        return Action::make('deleteApiToken')
            ->icon('tabler-trash')
            ->color('danger')
            ->size('sm')
            ->label(__('profile.api_tokens.delete'))
            ->requiresConfirmation()
            ->action(function (array $arguments): void {
                auth()->user()->tokens()->where('id', $arguments['token'])->delete();
                $this->loadApiTokens();

                Notification::make()
                    ->success()
                    ->title(__('profile.api_tokens.deleted'))
                    ->send();
            });
    }

    protected function logoutOtherBrowserSessionsAction(): Action
    {
        $form = auth()->user()->password !== null ? [
            TextInput::make('currentPassword')
                ->label(__('filament-panels::auth/pages/edit-profile.form.current_password.label'))
                ->validationAttribute(__('filament-panels::auth/pages/edit-profile.form.current_password.validation_attribute'))
                ->password()
                ->currentPassword(guard: Filament::getAuthGuard())
                ->revealable()
                ->required(),
        ] : [];

        return Action::make('logoutOtherBrowserSessions')
            ->icon('tabler-trash')
            ->size('sm')
            ->color('danger')
            ->label(__('profile.sessions.delete'))
            ->modalHeading(__('profile.sessions.delete'))
            ->requiresConfirmation()
            ->schema($form)
            ->action(function (array $data): void {
                $user = auth()->user();
                if ($user->password) {
                    /** @var string $password */
                    $password = $data['currentPassword'];
                    if (! Hash::check($password, $user->password)) {
                        return;
                    }

                    Auth::logoutOtherDevices($password);

                    request()->session()->put([
                        'password_hash_'.Auth::getDefaultDriver() => $user->password,
                    ]);
                }

                DB::table('sys_sessions')
                    ->where('user_id', '=', $user->id)
                    ->where('id', '!=', request()->session()->getId())
                    ->delete();

                Notification::make()
                    ->success()
                    ->title(__('profile.sessions.logout_success'))
                    ->send();

                $this->loadSessions();
            });
    }

    protected function deleteUserAccountAction(): Action
    {
        $form = auth()->user()->password !== null ? [$this->getCurrentPasswordFormComponent()] : [];

        return Action::make('deleteUserAccount')
            ->icon('tabler-trash')
            ->size('sm')
            ->color('danger')
            ->label(__('profile.delete_account'))
            ->modalHeading(__('profile.delete_account'))
            ->modalDescription(__('profile.delete_account_modal_description'))
            ->modalWidth(Width::Large)
            ->requiresConfirmation()
            ->schema($form)
            ->action(function (UserService $service): void {
                /** @var User $user */
                $user = auth()->user();

                $service->delete($user);

                Session::invalidate();
                Session::regenerateToken();

                $this->redirect(Filament::getLoginUrl());
            });
    }

    private function loadOidcProviders(): void
    {
        $service = app(OidcService::class);
        $enabled = $service->getEnabledProviders();

        $connected = auth()->user()->providers;

        $this->oidcProviders = [];
        foreach ($enabled as $slug => $data) {
            $connection = $connected->firstWhere('provider_name', $slug);
            $this->oidcProviders[$slug] = [
                'label' => $data['label'],
                'is_connected' => $connection !== null,
                'id' => $connection?->id,
            ];
        }
    }

    private function loadApiTokens(): void
    {
        $this->apiTokens = auth()->user()->tokens()
            ->latest()
            ->get();
    }

    private function loadSessions(): void
    {
        /** @var Collection<int, object{ id: string, user_agent: string|null, ip_address: string|null, last_activity: int }> $sessions */
        $sessions = DB::table('sys_sessions')
            ->where('user_id', '=', \auth()->user()->id)
            ->latest('last_activity')
            ->get();

        $currentSessionId = request()->hasSession() ? request()->session()->getId() : null;

        $agent = new Agent();
        $this->sessions = [];
        foreach ($sessions as $session) {
            $agent->setUserAgent($session->user_agent);

            $this->sessions[] = [
                'device' => [
                    'is_desktop' => $agent->isDesktop(),
                    'platform' => $agent->platform(),
                    'browser' => $agent->browser(),
                ],
                'ip_address' => $session->ip_address,
                'is_current_device' => $session->id === $currentSessionId,
                'last_active' => $session->last_activity,
            ];
        }
    }
}
