FROM php:8.4-fpm-alpine
WORKDIR /app

ARG VERSION=dev
ENV APP_VERSION=${VERSION} \
    PHP_IDE_CONFIG="serverName=fin-tracker"

LABEL org.opencontainers.image.title="Fin-Tracker" \
    org.opencontainers.image.description="Household Finance Manager" \
    org.opencontainers.image.url="https://github.com/barthjs/fin-tracker" \
    org.opencontainers.image.source="https://github.com/barthjs/fin-tracker" \
    org.opencontainers.image.version=${VERSION} \
    org.opencontainers.image.licenses="MIT"

RUN addgroup -g 1000 application && \
    adduser -D -u 1000 -G application application

RUN apk add --no-cache \
        bash \
        curl \
        nginx \
        nodejs \
        npm \
        supervisor

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
COPY --from=mlocati/php-extension-installer:latest /usr/bin/install-php-extensions /usr/local/bin/
RUN install-php-extensions \
        intl \
        pdo_mysql \
        pdo_pgsql \
        xdebug \
        zip && \
    rm -f /usr/local/bin/install-php-extensions && \
    rm -rf /usr/local/etc/php-fpm.d/*.conf

RUN mv /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
COPY php/php.ini /usr/local/etc/php/conf.d/php.ini
COPY php/php-dev.ini /usr/local/etc/php/conf.d/php-dev.ini
COPY php/application.conf /usr/local/etc/php-fpm.d/application.conf

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/dev.conf /etc/nginx/conf.d/dev.conf

COPY supervisord.conf /etc/supervisord.conf
COPY supervisor.d/nginx.conf /etc/supervisor.d/nginx.conf
COPY supervisor.d/php-fpm.conf /etc/supervisor.d/php-fpm.conf

EXPOSE 80 5173
ENTRYPOINT ["supervisord", "-c", "/etc/supervisord.conf"]
