# Apache, Composer, PHP
FROM webdevops/php-nginx-dev:8.3-alpine

# Labels
LABEL vendor="barthjs"
LABEL maintainer="barthjs"
LABEL org.opencontainers.image.url="https://github.com/barthjs/fin-tracker"
LABEL org.opencontainers.image.source="https://github.com/barthjs/fin-tracker"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.title="Fin-Tracker"

ENV PHP_DEBUGGER=xdebug \
    PHP_DISPLAY_ERRORS=1 \
    PHP_IDE_CONFIG="serverName=fin-tracker" \
    WEB_DOCUMENT_ROOT=/app/public \
    XDEBUG_CLIENT_PORT=9003 \
    XDEBUG_CLIENT_HOST=host.docker.internal \
    XDEBUG_START_WITH_REQUEST=yes

# Node.js, NPM
RUN apk add --no-cache nodejs npm
RUN npm install npm@latest -g

WORKDIR /app

COPY worker.conf /opt/docker/etc/supervisor.d/worker.conf
